name: "Setup Node and Install"
description: "Sets up Node.js, caches deps, and installs packages"
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22"
        cache: "npm"

    - name: Install dependencies
      run: npm ci
      shell: bash
