name: CI/CD Pipeline

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node & Install
        uses: ./.github/actions/setup-node

      - name: Run Tests
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node & Install
        uses: ./.github/actions/setup-node

      - name: Clean previous dist folder
        run: rm -rf dist dist_clean

      - name: Build project
        run: npm run build

      - name: Prepare clean deploy folder
        run: |
          mkdir dist_clean
          rsync -a --copy-links dist/ dist_clean/

      - name: Remove unnecessary files
        run: rm -f dist_clean/.DS_Store || true

      - name: Upload production-ready build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist_clean

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: dist
