name: Great User

# on: push
on: workflow_dispatch

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello, Great User! 👋 Your workflow is running."
