name: CI/CD Pipeline

on:
  push:
    branches:
      - main # run automatically on push to main
    paths-ignore:
      - README.md # ignore changes to README
  workflow_dispatch: # allows manual run via "Run workflow" button

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node & Install
        uses: ./.github/actions/setup-node

      - name: Run Tests
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: test # build runs only if test passes
    steps:
      - name: Setup Node & Install
        uses: ./.github/actions/setup-node

      - name: Build project
        run: npm run build

      - name: Upload production-ready build
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build # deploy runs only if build succeeds
    steps:
      - name: Download Dist Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Deployment
        run: echo '🚀 Deployment Completed'
