name: CI/CD Pipeline

on:
  push:
    branches:
      - main # run automatically on push to main
  workflow_dispatch: # allows manual run via "Run workflow" button

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm" # enable caching for node_modules

      - name: Install dependencies
        run: npm ci # faster, clean install for CI/CD

      - name: Run Tests
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: test # build runs only if test passes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload production-ready build
        uses: actions/upload-artifact@v4
        with:
          name: dist # artifact name
          path: dist # folder to upload

  deploy:
    runs-on: ubuntu-latest
    needs: build # deploy runs only if build succeeds
    steps:
      - name: Download Dist Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist # match the name used in build job
          path: dist # folder where it will be extracted

      - name: Deployment
        run: echo '🚀 Deployment Completed'
